### ISSUE TITLE
x/amount.go  link goes to DEX tutorial

### ISSUE THREAD

**Issue by antoineherzog** [iov-one/docs#125]
here we show codes from the DEX tutorial and also a link; You should show only the blog tutorial

 x/amount.go is a great example of extending the functionality, with code like:

// IsPositive returns true if the value is greater than 0
func (a *Amount) IsPositive() bool {
    return a.Whole > 0 ||
        (a.Whole == 0 && a.Fractional > 0)
}

// IsNegative returns true if the value is less than 0
func (a *Amount) IsNegative() bool {
    return a.Whole < 0 ||
        (a.Whole == 0 && a.Fractional < 0)
}

**Comment by orkunkl** [comment]
I will create a reasonable case for this and implement it!
