### ISSUE TITLE
please update the tutorial as you removed comment and like from the blog app

### ISSUE THREAD

**Issue by antoineherzog** [iov-one/docs#141]
https://docs.iov.one/docs/weave/tutorial/domain

**Comment by orkunkl** [comment]
@antoineherzog I could not get what this issue is for?

**Comment by antoineherzog** [comment]
to simplify the tutorial to the minimum of code ;) not decourage readers

**Comment by orkunkl** [comment]
Closed by https://github.com/iov-one/docs/pull/153
