### ISSUE TITLE
Fix code formatting under iov-name-service section 

### ISSUE THREAD

**Issue by orkunkl** [iov-one/docs#71]
Markdown has a cool feature named: [Code highligting](https://help.github.com/en/articles/creating-and-highlighting-code-blocks). There is code highlighting in the docs but their language is not specified.  Some of the code does not have a specified language.

**Comment by davepuchyr** [comment]
Nice catch!  When you see something like that please fix it and create a PR right away.  At least I got 5/6 right. :)

**Comment by orkunkl** [comment]
Sure :+1:
